### ISSUE TITLE
Simplification leads to incorrect normals on flat surfaces

### ISSUE THREAD

**Issue by traking** [zeux/meshoptimizer#406] opened 2022-01-27 07:54 UTC
Hi!

I'm using `meshopt_simplify(..., target_error = 1e-2, target_index_count = size_t(src_indices.size() * 0.5f)) ` and getting following results with attached mesh (in .OBJ):

As you can see there are some incorect normals being selected. Is there anything that I can adjust in algorithm in order to fix this behavior?

Thanks!
![normals](https://user-images.githubusercontent.com/8815172/151312294-d8edad14-080b-4201-a2fb-d1701b7166c3.png)
[desk.zip](https://github.com/zeux/meshoptimizer/files/7948589/desk.zip)

**Comment by zeux** [comment] 2022-01-30 02:50
This is a duplicate of #158; it requires the simplifier to actually compare the normal metric/error during simplification which currently isn't done. Of course you can, as a temporary measure, recompute normals post-simplification to work around it.

**Closed by zeux** 2022-01-30 02:50 UTC
Labels: bug
