### ISSUE TITLE
Replace mesh rather than generate new

### ISSUE THREAD

**Issue by christopher-rollinson** [zeux/meshoptimizer#252] opened 2021-03-09 15:50 UTC
Is it possible to overwrite existing meshes rather than create child objects? I've tried to use -kn, but I'm assuming that's not exactly what it's for. I've attached two screenshots of my glb, before and after optimization to try and show what I mean.

The main reason I'm asking is because I'm months into a project at this point and reference and manipulate a good chunk of the meshes in this glb. So having to work around the fact that it has become a transformNode might not be so straightforward. 

![original](https://user-images.githubusercontent.com/39518051/110497411-531e5280-80ee-11eb-8e75-53d61c5a8a61.PNG)
![optimised](https://user-images.githubusercontent.com/39518051/110497414-531e5280-80ee-11eb-8111-dd133ac4588f.PNG)

Thanks,
Chris

**Comment by zeux** [comment] 2021-03-09 16:19
This is a side effect of quantizing position data which needs an extra transform. I have plans to experiment with alternative quantization implementations that use meshopt compression codecs instead but I am *very* short on time in the last and next few weeks so this won't happen immediately.

Out of curiosity, are these meshes skinned? For skinned meshes in theory the extra node isn't necessary; gltfpack inserts it for consistency and to work around culling issues with three.js but that in theory could be disabled with an extra option. But regardless I suspect it's not too difficult to generalize the code that works with the scene, e.g. if you need to work with the meshes by toggling their visibility you could implement a function that toggles visibility for an entire subtree regardless of whether the root is a node or a mesh.

**Comment by zeux** [comment] 2021-03-25 04:36
I'm tracking the alternative implementation for compression in my offline TODO list as it's currently unknown how effective it is going to be and it might not be the perfect solution here necessarily - I'm going to close this because this is sort of by design otherwise and falls out of the specification for KHR_mesh_quantization.

**Closed by zeux** 2021-03-25 04:36 UTC
Labels: gltfpack
