### ISSUE TITLE
Visualisation difference when quantized and compressed

### ISSUE THREAD

**Issue by prajwalshelar** [zeux/meshoptimizer#395] opened 2022-01-06 07:29 UTC
We are using meshoptimizer to compress and quantize gltf files. When using compress and quantize separately, everything works as expected. But if we combine those operations, there is visualization difference in generated gltf files when they are rotated. Attached are the gltf files before and after compression and quantization .Any thoughts? /
[cube.zip](https://github.com/zeux/meshoptimizer/files/7820146/cube.zip)
![before](https://user-images.githubusercontent.com/97217462/148345082-9c855c45-ec50-4931-bcb8-1a961989c76b.PNG)
![after](https://user-images.githubusercontent.com/97217462/148345084-77073a11-d935-4f19-8b4d-b3fc581bc10b.PNG)

**Comment by zeux** [comment] 2022-01-08 02:55
I'm a little bit confused by this because I can't directly reproduce this.

Specifically:
- I can see the difference between cube_orig.gltf and cube.gltf in a viewer
- However, when I process cube_orig.gltf with a recent build of gltfpack, the resulting model looks the same as cube_orig.gltf
- cube.gltf from your .zip file has some odd parts, like a doublesided flag on the material even though it doesn't appear in the original file.

Can you verify whether the cube.gltf in your attachment was indeed produced from cube_orig.gltf, and note the exact command line you're using as well as which version of gltfpack this is (OS, whether it's npm or native binary, etc.)?

**Comment by zeux** [comment] 2022-01-08 02:56
... oh, wait, cube.gltf isn't even produced by gltfpack? I see the necessary extensions, but the metadata is off (generator should be gltfpack):

> {"version":"2.0","generator":"V1.0.0.0","extras":{"Author":"VI","InitialView":"UJhUVVU1QYTzP6qqqtKmxAXAVFVVla6x+j8AAACAeiL3vwAAAAA+UqwBCCxAGurvvz4sDHC9INoRCAA/CRAk6j+l80AqBSESQA==","CurrentView":"UPBPZDa5UWt11T/a6CCcfUsGwHFD/Wmt+wFAK2uS/4RN9r9AOgl0Rxinv6444MEOpPC/fHLd2Qki37+YDOoPU+XgP96oZ72iRuY/pfNAKgUhEkA="}

**Comment by zeux** [comment] 2022-01-14 04:29
I'm going to close this because there's no extra information provided and it's likely to be a bug in user code assuming this is using custom C++ code that uses meshoptimizer library but doesn't use gltfpack.

I'd recommend double checking that the buffer with normals uses meshopt_encodeFilterOct with a reasonable number of bits (eg 8) to encode the floating point input data, and that normals that are fed to meshopt_encodeFilterOct are unit length.

**Closed by zeux** 2022-01-14 04:29 UTC
Labels: bug
