### ISSUE TITLE
Avoid hole creation

### ISSUE THREAD

**Issue by Makio64** [zeux/meshoptimizer#656] opened 2024-02-06 21:36 UTC
On some models with extrem simplification ( example to make LoD ) the current algorithm create a lot of holes, is there a way to avoid it? 

Example on this model : https://sketchfab.com/3d-models/the-bust-of-napoleon-bonaparte-a177bf0e121641bea6cf1d58ad3efc5b

![image](https://github.com/zeux/meshoptimizer/assets/213351/a7ba9259-29b5-41a6-b435-53be26bd5dd8)

![image](https://github.com/zeux/meshoptimizer/assets/213351/4358b48b-19a1-4c33-9d72-0c2214ad9894)

**Comment by zeux** [comment] 2024-02-06 21:46
This is a duplicate of #346.

**Comment by zeux** [comment] 2024-02-06 21:46
(these are not topological holes, but due to shading the overlap of the resulting triangles looks like a gap in the geometry)

**Closed by zeux** 2024-02-06 21:46 UTC
Labels: enhancement

**Comment by Makio64** [comment] 2024-02-07 08:15
It's close as 'not planned'

I can give it a try as it's a necessary feature for us to use it in production : can you let me know what was the biggest difficulty you encountered and which part I should patch ?

I also thought about another approach making a secondary pass with IA trained to flip back the 'missing' face, do you think it's a good idea to? 

Thanks !

**Comment by zeux** [comment] 2024-02-07 17:14
"not planned" is just a GitHub issue default shorthand for:

![image](https://github.com/zeux/meshoptimizer/assets/1106629/368df653-f3f8-440f-8471-848373e304d0)

Further progress on this issue can be tracked via #346 - it's important to avoid duplicate issues for the same problem, and this one is already well described in that issue. The flipping situation was improved in previous version but further improvements are needed to fully prevent this.
