### ISSUE TITLE
gltfpack: Visible quantization artifacts on some scenes

### ISSUE THREAD

**Issue by MrMateo7** [zeux/meshoptimizer#466] opened 2022-08-18 16:20 UTC
I recently update to the latest version, `v.0.18.`
And realiced that now is very common after a simple optimization, even without compression the geometry looks "pixelated"
`gltfpack -i ... -o ...`

How it should look.
![image](https://user-images.githubusercontent.com/80969412/185444238-e4c3e36e-faeb-4312-8e7b-7f1c40270b47.png)

How it actually look.
![image](https://user-images.githubusercontent.com/80969412/185444093-1205228b-e8dc-4dcf-beaa-f86ed47f68f7.png)

I think this was due to some issue on my meshes, but after the update this happen almost every time.
with `v.0.16` this neeeeever happen

Any idea why this is happening?

**Comment by zeux** [comment] 2022-08-18 17:10
This looks as if something changed with quantization behavior between 0.16 and 0.18. Please attach the reproduction scene - without it it's impossible to diagnose cases like this. You can also pass `-vp 16` to improve this behavior.

**Comment by zeux** [comment] 2022-08-18 17:27
P.S. It's actually a little surprising that this scene used to work without quantization artifacts without extra options. You might want to use `-kn` flag because without it gltfpack will try to transform meshes to world space if they are static.

**Comment by MrMateo7** [comment] 2022-08-18 17:51
Thanks for answering!

1. Not necesary only on larger scenes. This is another one, very simple, in this case the character is rigged.
![image](https://user-images.githubusercontent.com/80969412/185459906-7f9e778e-24e3-414b-8f9a-a85e1ffc321f.png)
A thing is that I realized, it only happens in certain meshes with the property in common than the vertex are very close one of each other. (This could be a factor?)

3. `-vp 16` makes it looks better but still have trace of those squares. In `v0.16` with default value works perfectly.
4. Yeah sure, in this scene I need to use `-kn` specialy and other flags, I mention that no extra options to make it clear that even in the simplest way happen that "squarization".

**Comment by zeux** [comment] 2022-08-18 18:29
The scene above has the same issue on gltfpack 0.16 as far as I can tell. This came up before and is due to some odd export behavior that Blender has with skinned meshes and unit conversions, where it exports skinned geometry at a very different resolution vs non-skinned geometry. I am not sure if this is fixable, would need to think about the consequences of propagating scale from the skinned model into the vertex data.

**Comment by scarletsky** [comment] 2022-08-20 01:29
Same issue here. And I am using `gltfpack 0.18`

Before `gltfpack` process:
<img width="886" alt="image" src="https://user-images.githubusercontent.com/2386165/185723952-17665b5d-1068-4842-83f6-664c744192ac.png">


After `gltfpack -cc -kn -km -ke`
<img width="741" alt="image" src="https://user-images.githubusercontent.com/2386165/185723931-aa4d38eb-dea2-4a64-ad3c-6ce60979a1b1.png">

After `gltfpack -cc -kn -km -ke -vp 16`
<img width="696" alt="image" src="https://user-images.githubusercontent.com/2386165/185724013-913fbef5-e41d-4248-9e04-4c627a53ddfa.png">

And I got error `Unrecognized option -vpf` when adding `-vpf`

**Comment by zeux** [comment] 2022-08-20 01:42
Note: for any report in this thread that doesn't come with a link to the scene before the compression, it's going to be impossible to investigate whether it's something that can be improved or not. So far out of 3 examples here only one (from comment https://github.com/zeux/meshoptimizer/issues/466#issuecomment-1219770528) has been reproduced and traced to a skinning export issue, tracked in #433.

**Comment by scarletsky** [comment] 2022-08-22 03:14
Hi, I just have a test on a model on sketchfab
https://sketchfab.com/3d-models/fictional-supercar-v12-goblin-0a20e49ad5774d778567cb5c3f345786

I do these steps with the model:
- convert it to GLB with blender 3.2.2
- use `gltfpack -cc` to output a meshopt glb
- put the result to https://gltf-viewer.donmccurdy.com/ to see the result

The result is OK, and I modify the model, add a really large sphere on the model. This time, I got artifacts on `gltfpack -cc`, and got better result with `-vp 16`

OK [model.glb.zip](https://github.com/zeux/meshoptimizer/files/9390958/model.glb.zip)

OK [model_meshopt.glb.zip](https://github.com/zeux/meshoptimizer/files/9390960/model_meshopt.glb.zip)

OK [model_with_sphere.glb.zip](https://github.com/zeux/meshoptimizer/files/9390976/model_with_sphere.glb.zip)
![image](https://user-images.githubusercontent.com/2386165/185831470-7dc2266e-a2a4-427b-9f49-655460409588.png)


Artifacts [model_with_sphere_meshopt.glb.zip](https://github.com/zeux/meshoptimizer/files/9390977/model_with_sphere_meshopt.glb.zip)
![image](https://user-images.githubusercontent.com/2386165/185831405-b9d2f2e5-3ee3-4cdd-a291-205416373345.png)


Little artifacts [model_with_sphere_meshopt_vp16.glb.zip](https://github.com/zeux/meshoptimizer/files/9390978/model_with_sphere_meshopt_vp16.glb.zip)
![image](https://user-images.githubusercontent.com/2386165/185831371-69bdfd74-9e8d-4d8e-bf42-86ee802afaa6.png)

**Comment by zeux** [comment] 2022-10-04 03:44
Since no new examples have been posted, and https://github.com/zeux/meshoptimizer/issues/466#issuecomment-1221746038 is inevitable / expected, I'm going to assume that there's no regression and that the only tangible issue is with the skinned models and a very large scaling factor that Blender adds, which will be tracked / fixed by #433.

**Closed by zeux** 2022-10-04 03:44 UTC
Labels: bug, gltfpack
