### ISSUE TITLE
Any option to generate to keep separate bin files?

### ISSUE THREAD

**Issue by joaocc** [zeux/meshoptimizer#136] opened 2020-04-21 14:08 UTC
Is there any option to keep the bin files separate, optimizing them individually? Thx

**Comment by zeux** [comment] 2020-04-21 15:01
This will automatically happen if the output has a .gltf extension.

**Comment by joaocc** [comment] 2020-04-22 10:07
Thx for the quick response. We are testing with a source gltf with 300+ .bin files, and even if we state a .gltf output file, we only get a single .bin file.

`gltfpack -v -i ../source/model.gltf -o ./out/model.200422a.gltf`

results in a folder with a .gltf and a .bin
Here is the output with -v
`
input: 386 nodes, 363 meshes (469 primitives), 364 materials, 0 skins, 0 animations
input: 4444632 triangles, 13333896 vertices
output: 705251 triangles, 780699 vertices
output: 749 nodes, 363 meshes (363 primitives), 26 materials
output: JSON 234412 bytes, buffers 13599896 bytes
output: buffers: vertex 9368388 bytes, index 4231506 bytes, skin 0 bytes, time 0 bytes, keyframe 0 bytes, image 0 bytes
`

**Comment by zeux** [comment] 2020-04-22 13:51
Oh - this is by design. gltfpack groups buffer views so it’s not possible for it to preserve the original set of files, this the output is a single bin file for geometry and associated data. I am not sure it’s beneficial to split that without splitting the buffers as to display most parts of the scene you will need most buffers.

**Comment by joaocc** [comment] 2020-04-22 14:15
Thx. I understand.  
But there are some optimizations that, even it not optimal, could still be done in each file at the time, keeping the same number of target files. For instance, we could want to optimize only the number of vertexes and/or quantises in each .bin. 
Would this be possible (ie, treat each file individually)?
Thx

**Comment by zeux** [comment] 2020-04-22 14:44
The problem (apart from less optimal results) is that it would substantially change the program structure.

The way gltfpack works is by loading the entire scene, processing it, and then writing the new scene into the .gltf/.glb/.bin files - some elements of the scene are preserved verbatim right now, but most elements change.

So there's no concept (within how gltfpack is implemented) of "an input .bin file".

In theory it's possible to output separate files for separate locations in the scene, but doing this based on the source data doesn't seem best. It could be a long-term feature perhaps, I'm not sure. Just for clarity, why is it important that your asset contains many individual .bin files?

**Comment by joaocc** [comment] 2020-04-22 19:31
Thx for the clarification. It's not the number of individual .bin files that we are looking at, but rather keeping the ones we had in origin. We have a requirement where we rely on deduplicating different versions of uploads, and this relies on the fact that a complex scene only changes a few ".bin" files in every "save". If we cannot rely on it, we will have to store the whole scene every time. 
Same issue with download caching. It's easier to cache smaller non-changing files than have to download a single big file.
I understand this is prob a specific application, but in our case this can make a difference.

**Comment by zeux** [comment] 2020-04-23 05:31
Right - I think I understand the motivation. But I'm not sure how to reconcile this with gltfpack requirements - I really don't want to maintain logic long term that is dependent on the input file split. I feel like the possibly reasonable option is to use another program to pre-split the level according to the desired breakdown.

In the future gltfpack might gain some automatic options to split the output into multiple buffers, but this is *really* low on my priority list right now and I'd want to use heuristics based on object size / priority / spatial locality to group data together to optimize incremental loading instead of blindly trusting the input.

If anyone has other use cases for producing multiple .bin files, please comment on this issue so that I can gather more data on this.

**Comment by joaocc** [comment] 2020-04-23 11:15
Thanks for sharing. 
Just for clarification, in our case, we are not looking into splitting in arbitrary ways, but keeping a 1-1 mapping between input and output .bin files. 
In this conceptual scenario, we would be happy that the applicable subset of optimisation processes is done on each .bin independently, just like if they were independent. As mentioned above, in our use case, good-enough optimization would suffice, while keeping the split.
But naturally, I understand that this a very specific requirement, and the code is not structured that way, so changing this without other people having this use case would constrain the evolution.
Thx

**Comment by zeux** [comment] 2020-04-25 17:53
Right, I understand the requirements, they just aren't really compatible with what I'd ideally want to do with gltfpack going further.

My hope is that gltfpack can stay opinionated about the structure of the output, but can be sometimes guided by semantical hints, e.g. `-kn` says "names may be referenced externally and thus we can't make assumptions about the transform of these nodes staying static".

However, the buffer split is just an encoding artifact, it's not semantically meaningful and can evaporate under some transformations, e.g. merging the entire scene in a single .glb file; additionally buffers are pervasive, and tracking this relationship becomes complicated. What if some attributes are in one .bin and some others are in another .bin? What if gltfpack decides to discard some data that makes some .bin files redundant, should we drop the reference to that file? It's hard to preserve this well.

I feel like the best option for gltfpack here is to split the scene into multiple .gltf files at a higher level, before gltfpack processes the results - then updating a single file would naturally only require updating one .glb/.gltf+.bin/etc., and this splitting scheme would be compatible with other tools. My understanding is that 3D Tiles format (which is the only glTF-related initiative that allows composition of multiple glTF scenes as far as I know) follows this as well.

I'm going to close this issue since I don't anticipate it becoming a feature, but happy to hear about more cases where splitting into .bin within a single glTF scene is crucial.

**Closed by zeux** 2020-04-25 17:53 UTC
Labels: gltfpack

**Comment by joaocc** [comment] 2020-04-27 14:51
Thanks for the insightful explanation.
