### ISSUE TITLE
gltfpack: Empty node names removed when compressed?

### ISSUE THREAD

**Issue by ROBYER1** [zeux/meshoptimizer#551] opened 2023-04-25 13:55 UTC
When I compress the model below, the output compressed file has no names for the top meshes when imported in things like Three.js or imported with GLTFast in Unity.

![Image20230425144606](https://user-images.githubusercontent.com/10745594/234297624-a811ddc3-08c9-4032-9fcd-94393a01a4ad.png)
![Image20230425144604](https://user-images.githubusercontent.com/10745594/234297642-b38ca844-1761-4bd1-8cf1-57b37fa24502.png)

![NotWorking](https://user-images.githubusercontent.com/10745594/234299466-58684c4f-576a-44f6-bf5b-b55a6549e007.jpg)
![Working](https://user-images.githubusercontent.com/10745594/234299469-133f02ec-bfdf-4a80-9b08-9996279e8de9.jpg)

I used these commands as a test, neither fixed it
`gltfpack -tc -i Asset_Bike.gltf -o Asset_Bike.glb -cc -ac`
`gltfpack -tc -i Asset_Bike.gltf -o Asset_Bike.glb -cc -ac -kn`

Using this file as the gltf uncompressed, example compressed glb attached: 
[Downloads.zip](https://github.com/zeux/meshoptimizer/files/11323210/Downloads.zip)

**Comment by ROBYER1** [comment] 2023-04-25 15:15
This also happens when using -tc only without -cc so in theory the mesh file should be untouched but instead the node names of the top objects are deleted when using: gltfpack -i Asset_Bike.gltf -o Asset_Bike.glb -tc

**Comment by zeux** [comment] 2023-04-26 02:23
The behavior here is a little strange although mostly intentional... Here's what's happening, I believe:

- The meshes always lose their names. gltfpack always reprocesses the entire scene, and it's unclear how to preserve mesh names under transformations like merging or instancing. However, I think the behavior you see isn't due to mesh names - it's due to node names.
- When quantization is enabled, which it is by default (important for compression efficiency), the mesh nodes get a new, unnamed, node inserted under them to carry the dequantization matrix. See the following tree that gltf-viewer displays in console:

![image](https://user-images.githubusercontent.com/1106629/234450071-1a008474-7d2e-4356-bc8f-38f7785ae419.png)

- In Unity, what might be happening is that the skinned meshes get reparented to the root level because in glTF skinned meshes  don't inherit the transformation from the node they are attached to; gltfpack only adds this transform to work around Three.JS bugs with how culling works by default for skinned geometry
- gltfpack without `-kn` will merge meshes between different nodes because it will assume node names are insignificant, so you just get a single skinned mesh attached at root level.

So, uhh, everything seems to sort of be working as designed, but I'm not sure what this leads to in your application. The general behavior of gltfpack (with `-kn`) is that it might insert intermediate nodes when they are required for correctness, but will never remove named nodes from the hierarchy. As such, code that is written using scene graph node names (not mesh names!) should still function correctly. But this could require changing the code a little bit, for example adjusting parameters of a mesh with a given name is best done by iterating through the subtree with a known node name instead, and processing all attached meshes there.

If you're using the most recent version of gltfpack (binary available in artifacts here https://github.com/zeux/meshoptimizer/actions/runs/4771373374, this wasn't released with a numbered release yet), you can use a new mode, `-vpf`, which will use a different way of representing positions that should still compress decently well, but should not disrupt the hierarchy as much. Accordingly, if you use `gltfpack -kn -vpf`, you should see a tree that mostly reflects the original tree. The mesh names will be lost, but the node names will be in tact as well as the hierarchy.

**Comment by ROBYER1** [comment] 2023-04-26 08:13
Currently in our Unity application, I am grabbing imported model names and appending animation to them from a separate file (to keep users from redownloading heavy model files, we separate out just the model and its various animations as separate files).

This is a bit of a hack but as you can see in the hierarchy of the model here, the empty nodes are renamed by GLTFast in Unity to Node-1, so I just check if the model name is 'Node-1' and search for a child called scene then search for a child of scene with the naming convention that we use which is 'Equipment_' then I rename the Node-1 objects to that Equipment_ title then everything works again.
![image](https://user-images.githubusercontent.com/10745594/234512521-dec2843a-5899-41e4-b289-7477aeec09dd.png)

However, that is just a hacky workaround for the behaviour seen here so I will investigate the build you linked and report my findings, thanks for the help.

**Comment by ROBYER1** [comment] 2023-05-03 15:58
> The behavior here is a little strange although mostly intentional... Here's what's happening, I believe:
> 
> * The meshes always lose their names. gltfpack always reprocesses the entire scene, and it's unclear how to preserve mesh names under transformations like merging or instancing. However, I think the behavior you see isn't due to mesh names - it's due to node names.
> * When quantization is enabled, which it is by default (important for compression efficiency), the mesh nodes get a new, unnamed, node inserted under them to carry the dequantization matrix. See the following tree that gltf-viewer displays in console:
> 
> ![image](https://user-images.githubusercontent.com/1106629/234450071-1a008474-7d2e-4356-bc8f-38f7785ae419.png)
> 
> * In Unity, what might be happening is that the skinned meshes get reparented to the root level because in glTF skinned meshes  don't inherit the transformation from the node they are attached to; gltfpack only adds this transform to work around Three.JS bugs with how culling works by default for skinned geometry
> * gltfpack without `-kn` will merge meshes between different nodes because it will assume node names are insignificant, so you just get a single skinned mesh attached at root level.
> 
> So, uhh, everything seems to sort of be working as designed, but I'm not sure what this leads to in your application. The general behavior of gltfpack (with `-kn`) is that it might insert intermediate nodes when they are required for correctness, but will never remove named nodes from the hierarchy. As such, code that is written using scene graph node names (not mesh names!) should still function correctly. But this could require changing the code a little bit, for example adjusting parameters of a mesh with a given name is best done by iterating through the subtree with a known node name instead, and processing all attached meshes there.
> 
> If you're using the most recent version of gltfpack (binary available in artifacts here https://github.com/zeux/meshoptimizer/actions/runs/4771373374, this wasn't released with a numbered release yet), you can use a new mode, `-vpf`, which will use a different way of representing positions that should still compress decently well, but should not disrupt the hierarchy as much. Accordingly, if you use `gltfpack -kn -vpf`, you should see a tree that mostly reflects the original tree. The mesh names will be lost, but the node names will be in tact as well as the hierarchy.

I can confirm using the  `gltfpack -kn -vpf`, you suggested with that unreleased build fixed our issue! object node names remained intact when compressing!

**Comment by ROBYER1** [comment] 2023-05-03 16:28
> Perfect - note that you should be able to use 0.19 (https://github.com/zeux/meshoptimizer/releases/tag/v0.19) that just came out a few days ago, as it has this feature.

I tried via the npm package 0.19 but get this error when running this command which worked fine with the standalone .exe:

`gltfpack -i Asset_Chains_01.gltf -o test.glb -tc -kn -vpf`

```
Error: gltfpack was built without BasisU support, texture compression is not available
Note: node.js builds do not support BasisU due to lack of platform features; download a native build from https://github.com/zeux/meshoptimizer/releases
```

**Comment by zeux** [comment] 2023-05-03 16:56
Yes, for texture compression, you need to use native builds - see the link above.

**Closed** 2023-05-04 05:23 UTC
Labels: bug, gltfpack
