### ISSUE TITLE
Simplification produces reversed faces

### ISSUE THREAD

**Issue by roenyroeny** [zeux/meshoptimizer#698] opened 2024-05-28 15:16 UTC
Simplifying this mesh produces output with 1 face reversed.
input wireframe:
![image](https://github.com/zeux/meshoptimizer/assets/13182141/a196c97b-edbb-4c42-a7c0-f44996296823)
output wireframe:
![image](https://github.com/zeux/meshoptimizer/assets/13182141/de4977a2-3e04-4c75-8b7f-3a6e74e9f36d)
output with backface culling showing 1 reversed face:
![image](https://github.com/zeux/meshoptimizer/assets/13182141/8f82a245-0c8e-4fd4-b99e-e9892d59de00)

[Here](https://github.com/zeux/meshoptimizer/files/15472108/repro.zip) is the input mesh, and a small repro to make sure the settings for the simplifier are just right.

The repro outputs a reduced.obj which should contains the rogue reversed face.
It should also output the following:
```
face 27 [18 14 16] is flipped
```

**Comment by zeux** [comment] 2024-05-28 16:18
Duplicate of #346

**Closed by zeux** 2024-05-28 16:18 UTC
Labels: bug

**Comment by zeux** [comment] 2024-05-28 16:54
P.S. Pretty sure it's a duplicate of the issue I linked (same symptom, can be resolved by changing threshold in `hasTriangleFlips` from `0` to `1e-9` - not a generally correct fix but still), but it's the best repro out of that entire issue by far in terms of being easy to investigate :) Thanks for preparing that!
