### ISSUE TITLE
Obtaining error limit after simplify

### ISSUE THREAD

**Issue by reduz** [zeux/meshoptimizer#203] opened 2020-12-16 22:49 UTC
So, I have a question about how simplify works. Common sense makes me think one would aim for a target simplification (say, half of indices), and then obtain the error threshold (in normalized model dimensions), so when showing the model one can have a good idea at which distance (based on camera fov and resolution) the LOD change should take place.

I don't see this information returned in the simplify function, so how is one supposed to use this?

**Comment by zeux** [comment] 2020-12-16 23:14
This looks like it's a duplicate of #59?

There's two ways in theory to drive the process - shoot for the target ratio and use the error to set up LOD distances, or have an existing notion of acceptable error for all LOD levels (with set distances), and get the target ratio from that.

Right now the interface is designed for the latter use case, where you can specify the error bound and the simplifier will get as close to the desired ratio as possible, but yeah getting the error out would also be good. I'm planning to spend some time on the simplification in the next couple of weeks, so I can prioritize this.

**Comment by reduz** [comment] 2020-12-16 23:31
I'm working on this now, and I need this feature to continue,  so I would gladly send a PR if you wish by optionally returning sqrt(c.error), but I am not sure if this is enough, as I need to multiply it by the model size (which by the way its a bit confusing too, I had to dig the source to understand that the coordinates are divided by the longest AABB axis size).

If there is anything else that should be done, I would gladly give it a try.

**Comment by zeux** [comment] 2020-12-16 23:58
There's a patch for this in the linked issue; it needs to be converted to the actual output parameter, I think I wanted to use this opportunity to introduce a settings struct but didn't have time to figure out a good forward-compatible API/ABI.

**Comment by reduz** [comment] 2020-12-17 13:08
Oh I missed the patch in the txt. Will give this a try and let you know how it goes. Many thanks!

**Comment by zeux** [comment] 2020-12-17 18:10
Closing in favor of #59, we can continue the discussion there.

**Closed by zeux** 2020-12-17 18:10 UTC
Labels: enhancement, simplification

**Comment by reduz** [comment] 2020-12-17 18:17
:+1:

**Comment by zeux** [comment] 2020-12-30 06:49
Fixed by #216
