### ISSUE TITLE
Translate animation doesn't work after conversion

### ISSUE THREAD

**Issue by yaroslavnikiforov** [zeux/meshoptimizer#332] opened 2021-08-25 12:47 UTC
gltfpack verions: 0.16.0.
I use such flags for conversion: `-kn -at 24 -ar 16 -as 24 -ac -cc` to keep animation smooth. But without using them translate also doesn't work. See attached recording (left - before conversion, right - after)

https://user-images.githubusercontent.com/42115630/130793045-3416a7d1-3ee7-4817-ab3d-34443fe5704e.mov

**Comment by zeux** [comment] 2021-08-25 14:48
Could you check if this issue still exists in latest builds? You can grab one from artifacts in https://github.com/zeux/meshoptimizer/actions/runs/1165347806. Want to make sure this isn’t a duplicate of https://github.com/zeux/meshoptimizer/issues/278

**Comment by zeux** [comment] 2021-08-25 14:49
If the issue does happen with latest builds I will need the scene on question to investigate.

**Comment by zeux** [comment] 2021-09-08 03:59
I've looked at the model in question. The problem is that gltfpack removes the translate track from this model completely, as it decides that it's not significantly contributing to the result. This is because the track in question has a range of motion that's considered too small - the threshold is at 0.001 atm, and this animation moves in the range of 0.0002.

The reason why this is a problem in this case though is that the model is tiny - I'm not sure what the implied units are in this model, but the extents of the mesh attached to the animated note look to be ~0.003.

If you want a workaround you'd need to edit the source, unfortunately, as no command line parameter currently configures this threshold. I need to figure out what the best solution here is, this might mean `-ac` parameter needs to change to stop collapsing near-constant tracks into a single keyframe...

**Closed** 2021-09-08 07:57 UTC
Labels: bug, gltfpack
